### ISSUE TITLE
Disable splash animation on AnimatedIcon

### ISSUE THREAD

**Issue by PHPadawan** [fluttercommunity/backdrop#38]
Hi,

is there a way to disable the splash animation on the AnimatedIcon?

**Comment by WieFel** [comment]
You can set a custom `leading` widget on your `BackdropAppBar` in order to achieve this. Add the following to the app bar:

```dart
leading: Builder(
  builder: (BuildContext context) => IconButton(
      icon: AnimatedIcon(
      icon: AnimatedIcons.close_menu,
      progress: Backdrop.of(context).controller.view,
      ),
      onPressed: () => Backdrop.of(context).fling(),
      splashColor: Colors.transparent,
      highlightColor: Colors.transparent,
  ),
),
```

`Builder` is necessary to be able to access the backdrop widget from within the build context.
The `IconButton` is basically the same as [here](https://github.com/fluttercommunity/backdrop/blob/043f6e043c7c86ccdb36aaa7fdd306486e3ccae4/lib/button.dart#L42). Setting `splashColor` and `highlightColor` of the `IconButton` to `Colors.transparent` gives the splash animation a transparent color (see [here](https://stackoverflow.com/questions/49107295/how-to-disable-splash-highlight-of-flatbutton-in-flutter))

**Comment by PHPadawan** [comment]
Thank you very much, works great! :)
