### ISSUE TITLE
Reverse curve for expanding/shrinking BackdropScaffold

### ISSUE THREAD

**Issue by rtr-dnd** [fluttercommunity/backdrop#72]
**Is your feature request related to a problem? Please describe.**
I want to set different animation curves for expanding/shrinking the scaffold.
I tried to set the animation curve to `ease`, and while expanding worked fine, shrinking looked weird because `ease` animation is asymmetric. Similar issue below:
https://github.com/flutter/flutter/issues/39086

**Describe the solution you'd like**
As shown in the issue above, I want to set `reverseCurve` property of `CurvedAnimation` here:
https://github.com/fluttercommunity/backdrop/blob/01f118eeb4e066124019d5a8de62b34ec5b17bf0/lib/scaffold.dart#L459

And maybe the animation curve should default to `ease` instead of `easeInOut`...? Because that's the recommended curve in MD specs.
https://material.io/design/motion/speed.html#easing

**Comment by WieFel** [comment]
@rtr-dnd ok, we can add a new property `reverseAnimationCurve` which defaults to `animationCurve.flipped`, as described in the mentioned issue. We can make `animationCurve` default to `Curves.ease` instead of `Curves.easeInOut` too (also if I cannot notice much difference between the two :D)

@daadu is that ok? I can do the changes and make PR

**Comment by daadu** [comment]
@WieFel You have my blessings!

**Comment by daadu** [comment]
This has landed with [v0.5.0 on pub.dev](https://pub.dev/packages/backdrop/versions/0.5.0). @rtr-dnd Thanks for suggesting it. Please check yourself in REAMDE!!
